### PR TITLE
Bucket list

### PR DESCRIPTION
**Pull request by VilliGunn**

### CODE REVIEW

**Comment by plouc** [comment]
@VilliGunn why did you closed this one to ?

**Comment by VilliGunn** [comment]
Ahh sorry, I was going to PR our fork. Not finished yet.

**Comment by plouc** [comment]
So sad :(

**Comment by plouc** [comment]
BTW, I saw there's no component tests for now, if you want any clue on it, you should have a look on the latest work on https://github.com/plouc/mozaik-ext-github/tree/master/test, if you have some questions, don't hesitate to answer on https://gitter.im/plouc/mozaik.

**Comment by plouc** [comment]
And perhaps you could use the [eslint config used on the other extensions](https://github.com/plouc/mozaik-ext-github/blob/master/.eslintrc)

**Pull request closed without merging**
